services:
  - type: web
    name: PinBook
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MAPPLS_CLIENT_ID
        sync: false
      - key: MAPPLS_CLIENT_SECRET
        sync: false
      - key: AZURE_OPENAI_API_KEY
        sync: false
      - key: AZURE_OPENAI_ENDPOINT
        sync: false
      - key: AZURE_OPENAI_API_VERSION
        value: 2024-02-15-preview
      - key: AZURE_OPENAI_DEPLOYMENT_NAME
        sync: false
      - key: GOOGLE_PLACES_API_KEY
        sync: false
      - key: CONTACTOUT_API_KEY
        sync: false
